- GENERAL_SETTINGS:

- WEB_UI:
    WEB_Driver: "Chrome"                     # 浏览器驱动
    WEB_URL: 'http://localhost:5173/#/login' # Web测试地址

- APP_UI:
    APPIUM_HOST: 'http://localhost:4723'     # Appium2 服务器地址
    APP_Platform: 'Android'                  # 平台名称, Android 或 IOS

    Android_Options:
      platformName: 'Android'                # 安卓平台, adb shell getprop ro.product.brand
      platformVersion: '12'                  # 系统版本, adb shell getprop ro.build.version.release
      deviceName: '127.0.0.1:16384'          # 设备名称或调试端口, adb devices
      appPackage: 'com.android.browser'      # app包名, adb shell dumpsys window | findstr mCurrentFocus
      appActivity: '.BrowserActivity'        # 启动页面, adb shell dumpsys window | findstr mCurrentFocus
      automationName: 'uiautomator2'         # 测试引擎
      autoGrantPermissions: True             # 自动授予权限
      noReset: True                          # 启动app时不要清除app里的原有的数据
      fullReset: False                       # 是否清理app缓存数据
      newCommandTimeout: 3600                # 会话超时时间
      connectHardwareKeyboard: True          # 是否连接硬件键盘

    IOS_Options:
      platformName: 'ios'                    # IOS平台
      platformVersion: '12'                  # 系统版本